name: Build VLC on macOS

on:
 workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Checkout VLC source code
      uses: actions/checkout@v2
      with:
        repository: videolan/vlc
        ref: master

    - name: Install dependencies
      run: |
        brew install automake gettext libtool
        brew link gettext --force

    - name: Build VLC
      run: |
        ./bootstrap
        mkdir build && cd build
        ../extras/package/macosx/configure.sh --disable-lua
        make

    - name: Upload VLC
      uses: actions/upload-artifact@v2
      with:
        name: VLC
        path: |
          build/vlc-*-macosx.dmg
          build/bin/vlc-cache-gen
